codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default: off
      backend:
        target: 50%
        flags: backend

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
      
flags:
  # filter the folder(s) you wish to measure by that flag
  backend:
    # only include files in the backend folder
    paths:
      - leveldb/
      
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
